kind: pipeline
type: docker
name: "unit-test"

platform:
  os: linux
  arch: amd64

workspace:
  path: "/drone/src"

steps:
  - name: "jest unit test"
    image: node:12.20.2
    commands:
      - yarn install
      - yarn test-unit-ci
  - name: "coveralls"
    image: lizheming/drone-coveralls
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: coveralls_token
    settings:
      files:
        - ./coverage/lcov.info
      debug: true
---
kind: pipeline
type: docker
name: "e2e-test"
steps:
  - name: "cypress e2e test"
    # image: cypress/included:3.4.0
    # https://hub.docker.com/r/cypress/browsers/tags?page=1&ordering=last_updated
    image: cypress/browsers:node14.16.0-chrome90-ff88
    commands:
      - yarn install
      - yarn test-e2e-ci
---
kind: pipeline
type: docker
name: "build"
steps:
  - name: "push to git(master)"
    image: node:12.20.2
    when:
      branch:
        - master
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - . ./check-version.sh

depends_on:
  - "unit-test"
  - "e2e-test"
