kind: pipeline
type: docker
name: unit-test

platform:
  os: linux
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: 'jest unit test'
    image: node:12.20.2
    commands:
      - yarn install
      - yarn test
  - name: cypress-test
  image: compose:1.28.4
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - up -f e2e.docker-compose.yml

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
