kind: pipeline
type: docker
name: test-to-publish

platform:
  os: linux
  arch: amd64

workspace:
  path: "/drone/src"

steps:
  - name: "jest unit test"
    image: node:12.20.2
    commands:
      - yarn install
      - yarn test-unit-ci
  - name: "cypress e2e test"
    image: cypress/included:3.4.0
    commands:
      - rm -rf node_modules
      - yarn install
      - yarn test-e2e-ci
  - name: "push to git(master)"
    image: node:12.20.2
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - . ./check-version.sh
