kind: pipeline
type: docker
name: unit-test

platform:
  os: linux
  arch: amd64

workspace:
  path: "/drone/src"

steps:
  - name: "jest unit test"
    image: node:12.20.2
    commands:
      - yarn install
      - yarn test-unit-ci
---
kind: pipeline
type: docker
name: e2e-test
steps:
  - name: "cypress e2e test"
    image: cypress/included:3.4.0
    commands:
      - yarn install
      - yarn test-e2e-ci
