export const STORE_WEBSITES = 'STORE_WEBSITES';
export const STORE_WEBSITES_INDEX = 'STORE_WEBSITES_INDEX';
export const STORE_TASKS = 'STORE_TASKS';
export const STORE_TASKS_INDEX = 'STORE_TASKS_INDEX';
